################################### English language #####################################
[en]
languageName = "EN"
languageCode = "en-US"
contentDir = "content/english"
weight = 1
[en.params]
########### footer content ##########
footer_menu_left = "Contact info"
footer_menu_middle = "Sitemap"
footer_menu_right = "Policies"
footer_content = ""


################################### Español language #####################################
[es]
languageName = "ES"
languageCode = "es"
contentDir = "content/español"
weight = 2
[es.params]
########### footer content ##########
footer_menu_left = "Info contacto"
footer_menu_middle = "Map del sitio"
footer_menu_right = "Políticas"
footer_content = ""


################################### Catalan language #####################################
[ca]
languageName = "CAT"
languageCode = "ca"
contentDir = "content/catalan"
weight = 3
[ca.params]
########### footer content ##########
footer_menu_left = "Info contacte"
footer_menu_middle = "Mapa del lloc"
footer_menu_right = "Polítiques"
footer_content = "" 