# main menu
[[main]]
name = "Inici"
url = ""
weight = 1


[[main]]
name = "Sobre Nosaltres"
url = "/about"
weight = 2

[[main]]
name = "Col·laboracions"
url = "/collaborations"
weight = 3

[[main]]
name = "Contacte"
url = "/contact"
weight = 4


# footer menu left
[[footer_left]]
name = "Sobre Nosaltres"
url = "/about"
weight = 1

[[footer_left]]
name = "Equip"
url = "/team"
weight = 2

[[footer_left]]
name = "Com Funciona"
url = "/how-it-works"
weight = 3

[[footer_left]]
name = "Carreres"
url = "/career"
weight = 4


# footer menu middle
[[footer_middle]]
name = "CRM"
url = "/products/product-1"
weight = 1

[[footer_middle]]
name = "Help Desk"
url = "/products/product-2"
weight = 2

[[footer_middle]]
name = "Lloc de Treball"
url = "/products/product-3"
weight = 3

[[footer_middle]]
name = "Analitiques"
url = "/products/product-4"
weight = 4

# footer menu right
[[footer_right]]
name = "Preguntes Freqüents"
url = "/faq"
weight = 1

[[footer_right]]
name = "Contacte"
url = "/contact"
weight = 2

[[footer_right]]
name = "Politica de Privacitat"
url = "/privacy-policy"
weight = 3

[[footer_right]]
name = "Termes i Condicions"
url = "/terms-conditions"
weight = 4
