# main menu
[[main]]
name = "Inicio"
url = ""
weight = 1

[[main]]
name = "Sobre Nosotros"
url = "/about"
weight = 2

[[main]]
name = "Colaboraciones"
url = "/collaborations"
weight = 3

[[main]]
name = "Contacto"
url = "/contact"
weight = 4

##menú pie izquierdo##

[[footer_left]]
name = "Edificio Camí Reial c/ Camí Reial, 13-17, 3a planta 43700 El Vendrell"
#url = "/about"
weight = 1

[[footer_left]]
name = "+34 659 696 741"
#url = "/team"
weight = 2

[[footer_left]]
name = "hola@nexoapex.com"
#url = "/how-it-works"
weight = 3

# [[footer_left]]
# name = "Carrera"
# url = "/career"
# weight = 4

##menú pie central##

[[footer_middle]]
name = "Sobre"
url = "/about"
weight = 1

[[footer_middle]]
name = "Proyectos"
url = "/collaborations"
weight = 2

[[footer_middle]]
name = "Contacto"
url = "/contact"
weight = 3

# [[footer_middle]]
# name = "Analítica"
# url = "/products/product-4"
# weight = 4

##menú pie derecho

[[footer_right]]
name = "Legal"
url = "/terms-conditions"
weight = 1

[[footer_right]]
name = "Política de privacidad"
url = "/privacy-policy/"
weight = 2

[[footer_right]]
name = "Cookies"
url = "/cookies"
weight = 3

# [[footer_right]]
# name = "Términos y Condiciones"
# url = "/terms-conditions"
# weight = 4
