# main menu
[[main]]
name = "Inici"
url = ""
weight = 1


[[main]]
name = "Sobre Nosaltres"
url = "/about"
weight = 2

[[main]]
name = "Col·laboracions"
url = "/collaborations"
weight = 3

[[main]]
name = "Contacte"
url = "/contact"
weight = 4

##menú peu esquerre##

[[footer_left]]
name = "Sepapaja tn 6, 15551 Tallinn Estònia"
#url = "/about"
weight = 1

[[footer_left]]
name = "+34 659 696 741"
#url = "/team"
weight = 2

[[footer_left]]
name = "hi@digitalavocados.com"
#url = "/how-it-works"
weight = 3

# [[footer_left]]
# name = "Carrera"
# url = "/career"
# weight = 4

##menú peu central##

[[footer_middle]]
name = "Sobre"
url = "/about"
weight = 1

[[footer_middle]]
name = "Projectes"
url = "/collaborations"
weight = 2

[[footer_middle]]
name = "Contacte"
url = "/contact"
weight = 3

# [[footer_middle]]
# name = "Analítica"
# url = "/products/product-4"
# weight = 4

##menú peu dret

[[footer_right]]
name = "Legal"
url = "/terms-conditions"
weight = 1

[[footer_right]]
name = "Política de privacitat"
url = "/privacy-policy/"
weight = 2

[[footer_right]]
name = "Galetes"
url = "/cookies"
weight = 3

# [[footer_right]]
# name = "Termes i Condicions"
# url = "/terms-conditions"
# weight = 4