# main menu
[[main]]
name = "Inicio"
url = ""
weight = 1


[[main]]
name = "Sobre Nosotros"
url = "/about"
weight = 2

[[main]]
name = "Colaboraciones"
url = "/collaborations"
weight = 3

[[main]]
name = "Contacto"
url = "/contact"
weight = 4


# footer menu left
[[footer_left]]
name = "Sobre Nosotros"
url = "/about"
weight = 1

[[footer_left]]
name = "Equipo"
url = "/team"
weight = 2

[[footer_left]]
name = "Como Funciona"
url = "/how-it-works"
weight = 3

[[footer_left]]
name = "Carreras"
url = "/career"
weight = 4


# footer menu middle
[[footer_middle]]
name = "CRM"
url = "/products/product-1"
weight = 1

[[footer_middle]]
name = "Help Desk"
url = "/products/product-2"
weight = 2

[[footer_middle]]
name = "Lugar de Trabajo"
url = "/products/product-3"
weight = 3

[[footer_middle]]
name = "Analiticas"
url = "/products/product-4"
weight = 4

# footer menu right
[[footer_right]]
name = "Preguntas Frecuentes"
url = "/faq"
weight = 1

[[footer_right]]
name = "Contacto"
url = "/contact"
weight = 2

[[footer_right]]
name = "Politica de Privacidad"
url = "/privacy-policy"
weight = 3

[[footer_right]]
name = "Terminos y Condiciones"
url = "/terms-conditions"
weight = 4
