# main menu
[[main]]
name = "Home"
url = ""
weight = 1


[[main]]
name = "About"
url = "/about"
weight = 2

[[main]]
name = "Collaborations"
url = "/collaborations"
weight = 3

[[main]]
name = "Contact Us"
url = "/contact"
weight = 4


# footer menu left
[[footer_left]]
name = "Edificio Camí Reial c/ Camí Reial, 13-17, 3a planta 43700 El Vendrell"
# url = "/about"
weight = 1

[[footer_left]]
name = "+34 659 696 741"
# url = "/team"
weight = 2

[[footer_left]]
name = "hi@nexoapex.com"
# url = "/how-it-works"
weight = 3

# [[footer_left]]
# name = "Career"
# url = "/career"
# weight = 4


# footer menu middle
[[footer_middle]]
name = "About"
url = "/about"
weight = 1

[[footer_middle]]
name = "Projects"
url = "/collaborations"
weight = 2

[[footer_middle]]
name = "Contact"
url = "/contact"
weight = 3

# [[footer_middle]]
# name = "Analytics"
# url = "/products/product-4"
# weight = 4

# footer menu right
[[footer_right]]
name = "Legal"
url = "/terms-conditions"
weight = 1

[[footer_right]]
name = "Privacy Policy"
url = "/privacy-policy/"
weight = 2

[[footer_right]]
name = "Cookies"
url = "/cookies"
weight = 3

# [[footer_right]]
# name = "Terms & Conditions"
# url = "/terms-conditions"
# weight = 4
